### ISSUE TITLE
Doesn't compile on Ubuntu Bionic 18.04 (due to GLM version)

### ISSUE THREAD

**Issue by antgel** [acaudwell/Gource#145]
Two main errors:
```
/usr/include/glm/gtx/norm.hpp:21:3: error: #error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~
In file included from src/core/gl.h:27:0,
                 from src/core/texture.h:34,
                 from src/gource_settings.h:23,
                 from src/user.h:21,
                 from src/action.h:21,
                 from src/action.cpp:18:
src/core/vectors.h:41:2: error: #error This software is currently not compatible with
GLM 0.9.9 use GLM 0.9.8 instead
 #error This software is currently not compatible with GLM 0.9.9 use GLM 0.9.8 instead
  ^~~~~
```

**Comment by acaudwell** [comment]
Basically GLM 0.9.9 a2 shouldn't be in Ubuntu/Debian. It's an alpha and the developer changed it so the vectors are no longer initialized to zero so anything written against all earlier versions of GLM probably has bugs. This is why I haven't made it compile since the code is riddled with bugs now.

I guess I may be forced to bake GLM 0.9.8.5 into Gource to work around it since no one else seems to care.

**Comment by antgel** [comment]
Ouch. Thanks for the update, and hope to have a solution one way or another.

**Comment by acaudwell** [comment]
I've made a debian bug report about it: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892861

**Comment by acaudwell** [comment]
I've changed Gource to include its own fixed version of GLM: https://github.com/acaudwell/Gource/commit/4d0902bb1d5912208ae6136252bc88da7716c2e1
You may need to run autogen.sh to check out the glm submodule.

**Comment by antgel** [comment]
`git pull & make distclean && autogen.sh && ./configure && make` resulted in the same errors. Have I missed something?

**Comment by acaudwell** [comment]
My guess is autogen.sh didn't run (should be ./autogen.sh as its in the repo).

If it doesn't work after that check src/core/glm directory exists and the commit 'Fix compilation on GCC 7 minor versions by treating them as GCC 7.2.' is checked out. There should also be a reference to src/core/glm in the newly generated Makefile.

I've added a check so that configure will give an error if src/core/glm/glm/glm.hpp isn't found.

**Comment by acaudwell** [comment]
For me: 
git submodule update --recursive
Run from the gource repo checks out the glm submodule. I guess this doesn't do that for you? What does `git --version` say?

**Comment by acaudwell** [comment]
I've changed the command in autogen.sh to `git submodule update --init --recursive` hopefully that fixes it.

**Comment by antgel** [comment]
Looking good, thanks for the support and "fix". :)

**Comment by acaudwell** [comment]
libglm-dev has been updated in Debian and Bionic with an optional feature restoring the old constructor behavior so Gource works with it again without the work around.
